# Site settings
title: Fields Construction
email: bfieldsconstruction+website@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  General Contractor serving Yolo County area home remodel and repair. 
baseurl:  # the subpath of your site, e.g. /blog/
url: "https://fields.contstruction" # the base hostname & protocol for your site

# User setting
owner: Fields Construction
facebook_username:
twitter_username:
github_username:
address:
  - line: Davis, California 95616
  - line: Yolo County
  # Feel free to add more lines here 
telephone: 
copyright: 

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Services